# Codecov configuration to make it a bit less noisy
coverage:
  ignore:
    - pymbar/tests/.*
    - pymbar/testsystems/.*
    - setup.py
    - versioneer.py
    - pymbar/_version.py
    - pymbar/old_mbar.py
  status:
    patch: false
    project:
      default:
        threshold: 50%
comment:
  layout: "header"
  require_changes: false
  branches: null
  behavior: default
  flags: null
  paths: null