language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
# make sure we have numpy and scipy installed
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get install -qq python-numpy python-scipy
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - "pip install . --use-mirrors"
  - "pip install -r requirements.txt --use-mirrors"
# command to run tests, e.g. python setup.py test
script: "python tests/test-harmonic-oscillators.py"

