language: python
python:
  - "2.7"
# make sure we have numpy and scipy installed
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get install -qq python-numpy python-scipy
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - "pip install . --use-mirrors"
#  - "pip install -r requirements.txt --use-mirrors" # using apt-get instead
# command to run tests, e.g. python setup.py test
script: 
  - nosetests

