package:
  name: pymbar-dev
  version: !!str 3.0.4.dev0

source:
  path: ../../

requirements:
  build:
    - python
    - setuptools
    - numpy 1.11.*
    - toolchain
  run:
    - python
    - numpy >=1.12
    - scipy
    - numexpr

test:
  requires:
    - nose
    - statsmodels
  imports:
    - pymbar
  commands:
    - nosetests pymbar --with-doctest --doctest-tests -v

about:
  home: https://github.com/choderalab/pymbar
  license: MIT
  summary: Python implementation of the multistate Bennett acceptance ratio (MBAR) method.
