package:
  name: pymbar
  version: !!str dev


requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - setuptools
    - numexpr    
  run:
    - python
    - cython
    - numpy
    - scipy
    - numexpr

test:
  requires:
    - nose
    - setuptools    
  imports:
    - pymbar
  commands:
    - nosetests pymbar -v --with-doctest

about:
  home: https://github.com/choderalab/pymbar
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: Python implementation of the multistate Bennett acceptance ratio (MBAR) method.
